name: Build VB.NET Program

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Install .NET Framework 4.6.2 Developer Pack
      run: |
        # Download the offline installer
        Invoke-WebRequest -Uri 'https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net462-developer-pack-offline-installer' -OutFile 'ndp462-devpack-kb3151934-enu.exe'

        # Install the developer pack
        Start-Process -Wait -FilePath 'ndp462-devpack-kb3151934-enu.exe'

        # Add the developer pack's tools to the PATH
        $env:PATH += ';C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.2 Tools\'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-artifacts
        path: ./publish

# Thanks EggBean
